#ifndef	_NSPISUPERVISOR_H
#define	_NSPISUPERVISOR_H	1


#define MAX_LENGTH_TCPBUFFER 262144

namespace nsPISupervisor {

	const unsigned short PIAGENT_PORT = 7789; 
	const unsigned short PISUPERVISOR_PORT = 7790; 
	const unsigned short PIESF_PORT = 7791;

	typedef enum _EM_EVENTID {
		EVENT_NONE = 0
			, EVENT_INIT_PISUPERVISOR = 100
			, EVENT_UNINIT_PISUPERVISOR = 101
			, EVENT_UNREGISTER = 102
			, EVENT_CHANGED_ONOFFLINEMODE = 103
			, EVENT_CHANGED_DLPPOLICY = 104
			, EVENT_CHANGED_DEVICE = 105
			, EVENT_EXECUTE = 106
			, EVENT_TTL = 107
			, EVENT_CHANGED_AGENT_STATUS = 108
			, EVENT_POST_AGENT_STATUS = 109
			, EVENT_REGISTER = 110
	}EM_EVENTID;

	typedef enum _EM_IPC_COMMAND{
		PIPE_COMMAND_PISUPERVISOR_TEST_N						= 1,
		PIPE_COMMAND_PISUPERVISOR_SYNC_REGISTER_N				= 1201,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_UNREGISTER_N			= 1203,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_ONCHANGE_ONOFFLINE_N	= 1204,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_ONCHANGE_POLICY_N		= 1205,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_TTL_N					= 1206,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_DEVICELOG_N				= 1207,
		PIPE_COMMAND_PISUPERVISOR_ASYNC_EVENT_N					= 1208,
		//start: Redmine #148385 ----------
		PIPE_COMMAND_PISUPERVISOR_SYNC_QUARANTINEFILE_N			= 1209,
		PIPE_COMMAND_PISUPERVISOR_SYNC_DELETE_QUARANTINEDFILE_N	= 1210,
		PIPE_COMMAND_PISUPERVISOR_SYNC_RELEASE_QUARANTINEDFILE_N = 1211,
		PIPE_COMMAND_PISUPERVISOR_SYNC_QUARANTINE_ADD_PID_N 	= 1212,
		PIPE_COMMAND_PISUPERVISOR_SYNC_QUARANTINE_REMOVE_PID_N 	= 1213,
		PIPE_COMMAND_PISUPERVISOR_SYNC_GET_QUARANTINE_ROOTPATH_N = 1214,
		PIPE_COMMAND_PISUPERVISOR_SYNC_GET_QUARANTINE_DISKSIZE_N = 1215,
        
        PIPE_COMMAND_PISUPERVISOR_NEED_DISK_AUTH_N              = 1300,
		//end: Redmine #148385 ----------
		PIPE_COMMAND_WRITE_REMOVAL_DRIVE_N						= 1701,
		PIPE_COMMAND_DELETE_FILE_N 								= 1801,
		PIPE_COMMAND_PROCESS_CONTENT_N							= 2001,
        PIPE_COMMAND_PROCESS_NETWORK_CONTENT_N					= 2003,
		PIPE_COMMAND_PIAGENT_QT_DISKFULL_MSG_N 					= 2548,
	}EM_IPC_COMMAND;

}
#endif // #ifndef _NSPISUPERVISOR_H
